name: Firmware Selector Test

on:
  push:
    paths:
      - ".github/workflows/*"
      - "www/**"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: www/
        css: true
